name: nbdev_env
channels:
  - defaults
  - conda-forge
dependencies:
  - dtale=1.8.0
  - jupyter=1.0.0
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - nbdime=2.0.0
  - numpy=1.18.1
  - pandas=1.0.3
  - pandas-profiling=1.4.1
  - python=3.8.2
  - scikit-learn=0.22.1
  - seaborn=0.10.0
  - pip:
    - fastscript==0.1.4
    - nbdev==0.2.16
    - packaging==20.3

