# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mult2": "dev_nb.ipynb"}

modules = ["core.py"]

doc_url = "https://this_user.github.io/demo_playground/"

git_url = "https://github.com/this_user/demo_playground/tree/main/"

def custom_doc_links(name): return None
