# AUTOGENERATED! DO NOT EDIT! File to edit: dev_nb.ipynb (unless otherwise specified).

__all__ = ['mult2']

# Cell
# This function multiplies values by two
def mult2(val):
    '''Returns double of the supplied input parameter val'''
    return 2 * val